version: "3.8"
services:
  game-league:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./data:/app/data
      - .:/app # Mount the current directory
    ports:
      - 5000:5000
    command: |
      sh -c "pip install --no-cache-dir Flask psycopg2-binary python-dotenv beautifulsoup4 requests &&
              python app.py"
    environment:
      - FLASK_ENV=development
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db # Ensure the database is started before the app
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data
      - ./data:/app/data
volumes:
  postgres_data: null
    # Named volume for PostgreSQL data storage

networks: {}
